version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: ./php/dockerfile
    volumes:
      - ./src:/var/www/laravel-todo-app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mariadb:10.6.18
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_todo_app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mariadb_data: