FROM php:8.3.9-apache

# シェルの設定
ENV SHELL /bin/bash

# パッケージリストの更新とパッケージのアップグレード
RUN apt-get update && apt-get upgrade -y

# パッケージのインストール
RUN apt-get install unzip

# PHPの拡張機能をインストール
RUN docker-php-ext-install pdo pdo_mysql

# Composerのインストール
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Apacheの設定
RUN a2enmod rewrite

# 作業ディレクトリの設定
WORKDIR /var/www/laravel-todo-app

# www-dataユーザーのUIDとGIDを1000に変更
RUN usermod -u 1000 www-data && groupmod -g 1000 www-data

# Apacheユーザーに変更(イメージ内に存在する作成済みの権限が制限されたユーザー)
RUN chown -R www-data:www-data /var/www/laravel-todo-app